# Generated by Django 4.2.4 on 2023-09-04 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_esporpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EsporPost',
            new_name='Slider',
        ),
    ]
