# Generated by Django 4.2.4 on 2023-09-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
